# Generated by Django 3.1.7 on 2021-04-18 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0012_auto_20210419_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_mode', models.CharField(choices=[('Delivered', 'Delivered'), ('PickUp', 'PickUp')], max_length=30)),
                ('subscribe_status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.item')),
            ],
            options={
                'verbose_name': 'Meal Subscription',
                'verbose_name_plural': 'Meal Subscriptions',
            },
        ),
    ]
