# Generated by Django 3.1.7 on 2021-04-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealsubscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealsubscription',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='mealsubscription',
            name='start_date',
        ),
        migrations.AddField(
            model_name='mealsubscription',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
