# Generated by Django 3.1.7 on 2021-04-24 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210424_2137'),
        ('mealsubscription', '0002_auto_20210419_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealsubscription',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='mealsubscription',
            name='item',
        ),
        migrations.RemoveField(
            model_name='mealsubscription',
            name='subscribe_status',
        ),
        migrations.AddField(
            model_name='mealsubscription',
            name='days_available',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='mealsubscription',
            name='delivery_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.location'),
        ),
        migrations.AddField(
            model_name='mealsubscription',
            name='orderitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.orderitems'),
        ),
        migrations.AddField(
            model_name='mealsubscription',
            name='payment_method',
            field=models.CharField(choices=[('Payroll', 'Payroll'), ('Credit', 'Credit')], default='Credit', max_length=30),
        ),
    ]
