# Generated by Django 3.1.7 on 2021-05-20 03:11

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_meal_name', models.CharField(max_length=150)),
                ('patron_first_name', models.CharField(max_length=150)),
                ('patron_last_name', models.CharField(max_length=150)),
                ('patron_email_address', models.CharField(max_length=50)),
                ('patron_phone_contact', models.CharField(max_length=50)),
                ('meal_reqest_time', models.TimeField(null=True)),
                ('meal_reqest_date', models.DateTimeField(blank=True, null=True)),
                ('order_quantity', models.IntegerField(default=0)),
                ('custom_meal_receipe', models.CharField(max_length=100)),
                ('custom_meal_ingredients', models.CharField(max_length=100)),
                ('request_order_status', models.CharField(choices=[('Incomplete', 'Incomplete'), ('Accepted', 'Accepted'), ('Prepared', 'Prepared'), ('Pending Delivery', 'Pending Delivery'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Pending', max_length=255)),
                ('custom_meal_price', models.FloatField(default=False)),
            ],
            options={
                'verbose_name': 'Custom Meal Order',
                'verbose_name_plural': 'Custom Meal Orders',
            },
        ),
        migrations.CreateModel(
            name='OnSiteLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=80)),
            ],
        ),
        migrations.RenameModel(
            old_name='Location',
            new_name='OffSiteLocation',
        ),
        migrations.AlterField(
            model_name='item',
            name='instructions',
            field=models.CharField(blank=True, choices=[('Pickup', 'Pickup'), ('Delivery Available', 'Delivery Available'), ('Both Available [Pickup & Delivery Available]', 'Both Available [Pickup & Delivery Available]')], max_length=250),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='slug', max_length=255),
        ),
        migrations.AlterField(
            model_name='mealsubscription',
            name='days_available',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=255),
        ),
        migrations.AlterField(
            model_name='mealsubscription',
            name='delivery_mode',
            field=models.CharField(choices=[('Delivered (On Site Campus)', 'Delivered (On Site Campus)'), ('Delivered (Off Site Campus) *limited sites', 'Delivered (Off Site Campus) *limited sites'), ('PickUp', 'PickUp')], max_length=255),
        ),
        migrations.AlterField(
            model_name='mealsubscription',
            name='payment_method',
            field=models.CharField(choices=[('Payroll', 'Payroll'), ('Credit', 'Credit')], default='Credit', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='delivery_mode',
            field=models.CharField(choices=[('Delivered (On Site Campus)', 'Delivered (On Site Campus)'), ('Delivered (Off Site Campus) *limited sites', 'Delivered (Off Site Campus) *limited sites'), ('PickUp', 'PickUp')], max_length=255),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='payment_method',
            field=models.CharField(choices=[('Payroll', 'Payroll'), ('Credit', 'Credit')], default='Credit', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], default='Active', max_length=255),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rslug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mealsubscription',
            name='delivery_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.onsitelocation'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='delivery_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.onsitelocation'),
        ),
    ]
