# Generated by Django 3.1.7 on 2021-06-22 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_place_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='serves_hot_dogs',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='serves_pizza',
        ),
    ]
