# Generated by Django 3.1.7 on 2021-05-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210521_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='pickup_location',
            field=models.CharField(default='USP Cafeteria', max_length=255),
        ),
    ]
