# Generated by Django 3.1.7 on 2021-05-28 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210528_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custommeal',
            old_name='meal_reqest_date',
            new_name='meal_request_date',
        ),
        migrations.RemoveField(
            model_name='custommeal',
            name='meal_reqest_time',
        ),
    ]
