# Generated by Django 3.1.7 on 2021-05-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210528_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='created_time',
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ManyToManyField(to='main.Item')),
            ],
        ),
    ]
