# Generated by Django 3.1.7 on 2021-05-29 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210529_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Food Item', 'verbose_name_plural': 'Food Items'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
        migrations.AddField(
            model_name='menu',
            name='show_users',
            field=models.BooleanField(default=False),
        ),
    ]
