# Generated by Django 3.1.7 on 2021-05-29 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210529_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='show_users',
        ),
    ]
