# Generated by Django 3.1.7 on 2021-05-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_menu_show_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.CharField(default='Menu Items Available', max_length=25),
        ),
    ]
