# Generated by Django 3.1.7 on 2021-05-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_menu_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='item',
            new_name='items',
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.CharField(blank=True, choices=[('Display', 'Display'), ('Notdisplayed', 'Notdisplayed')], max_length=25),
        ),
    ]
