# Generated by Django 3.1.7 on 2021-05-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210530_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='meal_menu',
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Display', 'Display'), ('Hide', 'Hide')], max_length=25),
        ),
    ]
