# Generated by Django 3.1.7 on 2021-05-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_location_pickup_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='pickup_location',
        ),
    ]
