# Generated by Django 3.1.7 on 2021-05-22 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_location_pickup_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='offsite',
        ),
        migrations.RemoveField(
            model_name='location',
            name='onsite',
        ),
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='location',
            name='category',
            field=models.CharField(choices=[('OnSite', 'OnSite'), ('OffSite', 'OffSite')], default='OnSite', max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, default='USP', max_length=50),
        ),
        migrations.AlterField(
            model_name='mealsubscription',
            name='delivery_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.location'),
        ),
        migrations.DeleteModel(
            name='OffSiteLocation',
        ),
        migrations.DeleteModel(
            name='OnSiteLocation',
        ),
    ]
