# Generated by Django 3.1.7 on 2021-05-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210527_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hide_menu',
            field=models.BooleanField(default=False),
        ),
    ]
