# Generated by Django 3.1.7 on 2021-04-24 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210424_2137'),
        ('mealsubscription', '0003_auto_20210424_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealsubscription',
            name='orderitem',
        ),
        migrations.AddField(
            model_name='mealsubscription',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer'),
        ),
        migrations.AddField(
            model_name='mealsubscription',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.item'),
        ),
    ]
